title: "Building websites in GitHub"
description: "This research project develops training materials for researchers wanting to learn building static project portfolio websites."
email: "robert.nagy@ed.ac.uk"
twitter: "https://twitter.com/thecarpentries"
twitterhandle: "@thecarpentries"
